### ISSUE TITLE
Move this repository to the zarr-org

### ISSUE THREAD

**Issue by constantinpape** [zarr-developers/zarr_implementations#18]
I think having this reference data is fairly useful. However, I think it's a bit hard to discover right now, so I think it would be good to move it to the zarr org to improve visibility (and also encourage more contributions ;)).

Any thoughts on this @joshmoore @alimanfoo @jakirham.

**Comment by joshmoore** [comment]
:+1: cc: @jakirkham

**Comment by jakirkham** [comment]
Fine by me

**Comment by constantinpape** [comment]
Ok, done :).

**Comment by jakirkham** [comment]
Ah great was going to ask if there was anything we needed to do to help with this. If anything else comes up, please let us know 🙂
