### ISSUE TITLE
zarr.js implementation

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/zarr_implementations#19]
cc: @manzt

**Comment by manzt** [comment]
Likely beyond the scope of this repo, but just a thought. Having something like the [can-i-use](https://caniuse.com/) tables would be cool to see if you're desired zarr is browser compatible. This observable notebook reads data from master in this repo.

example: https://observablehq.com/d/c5020efb6bcb04d9

<img width="1048" alt="Screen Shot 2021-02-25 at 5 21 49 PM" src="https://user-images.githubusercontent.com/24403730/109227220-f6d23f00-778d-11eb-99b4-33bbd66d4de9.png">

**Comment by manzt** [comment]
Oh, also @gzuidhof just so you are aware :)

**Comment by joshmoore** [comment]
Nice! Up to you I guess if it's "beyond this repo" or not. If it is, then this issue can probably be closed. But if you want to find a permanent home for the example, https://zarr-developers.github.io/zarr_implementations may be a choice.

**Comment by manzt** [comment]
Feel free to close the issue. We think about something more permanent elsewhere. Just wanted to float and idea/example.
