### ISSUE TITLE
zarrita (v3) implementation

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/zarr_implementations#22]
Integrate [Zarrita][0], the current reference implementation for the V3 spec, into the zarr_implementations repository by generating files with the file ending .zr3 for all currently implemented codecs. These files should be considered a third file type beside .zr and .n5. Initially, there will be no implementations other than Zarrita that can read these files, but as the first implementation it can be proactively merged to the mainline. As other implementations are added, there may need to be a review of the branch.

[0]: https://github.com/alimanfoo/zarrita

**Comment by manzt** [comment]
Let me know if there is interest in adding [`zarrita.js`](https://github.com/manzt/zarrita.js).

**Comment by joshmoore** [comment]
@manzt: unless you want to spike the v3 support outside of zarr.js, I imagine having a single implementation that can read both is ultimately more user-friendly.

**Comment by grlee77** [comment]
I think this was closed by #24, or is it being left open as a reminder to add zarrita.js?

**Comment by manzt** [comment]
I'd say feel free to close!
