### ISSUE TITLE
pyn5 data

### ISSUE THREAD

**Issue by clbarnes** [zarr-developers/zarr_implementations#8]
Add another N5 implementation to the pile!  If it's appriopriate, as it doesn't support zarr. 

https://github.com/pattonw/rust-pyn5

The core implementation is in rust, but it's generally used from python.

**Comment by constantinpape** [comment]
> Add another N5 implementation to the pile! If it's appriopriate, as it doesn't support zarr.

Sure still fine, any implementation is good to have.

**Comment by grlee77** [comment]
I think this was closed by #10?

**Comment by jakirkham** [comment]
Yeah I think so. Thanks Greg! @clbarnes if there are still missing things, please let us know 🙂
